# Generated by Django 3.1.2 on 2021-05-18 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.CharField(max_length=128)),
                ('salary', models.FloatField()),
                ('birth_date', models.DateField()),
            ],
        ),
    ]
